"""Regenerate runtime pins from the installed, verified dependency graph."""
import importlib.metadata
import tomllib
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

project = tomllib.loads(Path("pyproject.toml").read_text(encoding="utf-8"))
pending = [Requirement(r) for r in project["project"]["dependencies"]]
seen, versions = {}, {}
while pending:
    requirement = pending.pop()
    name = canonicalize_name(requirement.name)
    extras = set(requirement.extras) | {""}
    if name in seen and extras.issubset(seen[name]):
        continue
    seen.setdefault(name, set()).update(extras)
    distribution = importlib.metadata.distribution(name)
    versions[name] = distribution.version
    for raw in distribution.requires or []:
        child = Requirement(raw)
        include = child.marker is None
        for platform in ("linux", "win32"):
            for extra in seen[name]:
                environment = {**default_environment(), "sys_platform": platform, "extra": extra}
                if child.marker is not None and child.marker.evaluate(environment):
                    include = True
        if include:
            pending.append(child)
lines = ["# Runtime dependency closure; generated by scripts/lock_dependencies.py after verification."]
lines += [f"{name}=={version}" for name, version in sorted(versions.items())]
Path("requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Pinned {len(versions)} runtime packages.")
